import type { MetadataRoute } from 'next'

const SITE_URL = 'https://inno100.ai'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
    },
    /*
     * Two sitemaps on purpose. The first is ours, generated by app/sitemap.ts.
     * The second is served by Arenza through the /guides rewrite and lists the
     * articles they publish there — pages our own sitemap never sees, because
     * they are rendered on their server rather than built from this repo.
     */
    sitemap: [`${SITE_URL}/sitemap.xml`, `${SITE_URL}/guides/sitemap.xml`],
  }
}
